name: Deploy react
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ahmedfahmy168/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true ahmedfahmy168/react-test npm run test

      - run: docker build -t ahmedfahmy168/multi-client ./microservices/client
      - run: docker build -t ahmedfahmy168/multi-nginx ./microservices/nginx
      - run: docker build -t ahmedfahmy168/multi-server ./microservices/server
      - run: docker build -t ahmedfahmy168/multi-worker ./microservices/worker

      - run: docker push aahmedfahmy168/multi-client
      - run: docker push ahmedfahmy168/multi-nginx
      - run: docker push ahmedfahmy168/multi-server
      - run: docker push ahmedfahmy168/multi-worker
